//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxdSolutions.FusionLink.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RxdSolutions.FusionLink.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested Portfolio Column &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string ColumnNotFoundMessage {
            get {
                return ResourceManager.GetString("ColumnNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FusionLink Connection Id is {0}.
        /// </summary>
        internal static string ConnectionIdMessage {
            get {
                return ResourceManager.GetString("ConnectionIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Cell as Excel FusionLink Reference.
        /// </summary>
        internal static string CopyCellAsExcelReference {
            get {
                return ResourceManager.GetString("CopyCellAsExcelReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Row(s) as Excel FusionLink References.
        /// </summary>
        internal static string CopyTableAsExcelReference {
            get {
                return ResourceManager.GetString("CopyTableAsExcelReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting data... please wait.
        /// </summary>
        internal static string DefaultDataLoadingMessage {
            get {
                return ResourceManager.GetString("DefaultDataLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FusionLink.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoIcon {
            get {
                object obj = ResourceManager.GetObject("InfoIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load FusionLink.
        /// </summary>
        internal static string LoadFailureMessage {
            get {
                return ResourceManager.GetString("LoadFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading FusionLink....
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} clients connected.
        /// </summary>
        internal static string MultipleClientsConnectedMessage {
            get {
                return ResourceManager.GetString("MultipleClientsConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Excel with FusionLink.
        /// </summary>
        internal static string OpenFusionLinkExcel {
            get {
                return ResourceManager.GetString("OpenFusionLinkExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested Portfolio &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string PortfolioNotFoundMessage {
            get {
                return ResourceManager.GetString("PortfolioNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested portfolio &apos;{0}&apos; is not loaded. Please load in the FusionInvest client..
        /// </summary>
        internal static string PortfolioNotLoadedMessage {
            get {
                return ResourceManager.GetString("PortfolioNotLoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested position &apos;{0}&apos; is either not loaded or does not exist. Please load the positions portfolio in FusionInvest.
        /// </summary>
        internal static string PositionNotLoadedOrMissingMessage {
            get {
                return ResourceManager.GetString("PositionNotLoadedOrMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display FusionLink.
        /// </summary>
        internal static string ScenarioShowCaptionBarMessage {
            get {
                return ResourceManager.GetString("ScenarioShowCaptionBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display FusionLink.
        /// </summary>
        internal static string ShowFusionLinkScenarioName {
            get {
                return ResourceManager.GetString("ShowFusionLinkScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} client connected.
        /// </summary>
        internal static string SingleClientConnectedMessage {
            get {
                return ResourceManager.GetString("SingleClientConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Start / Stop FusionLink.
        /// </summary>
        internal static string StartStopButtonTooltip {
            get {
                return ResourceManager.GetString("StartStopButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopButtonText {
            get {
                return ResourceManager.GetString("StopButtonText", resourceCulture);
            }
        }
    }
}
